### ISSUE TITLE
A problem with the back-to-exit gesture

### ISSUE THREAD

**Issue by Carnivorec** [Xposed-Modules-Repo/ma.wanam.youtubeadaway#8] opened 2023-01-28 17:30 UTC
I downloaded the latest version 5.0.5. But the YouTube app just exited every time I used a back-to-exit gesture. Could you tell me how to solve this problem?

**Comment by Carnivorec** [comment] 2023-01-28 17:35
By the way, I am using YouTube version number 18.02.34

**Comment by cocci810123** [comment] 2023-01-29 10:05
Yes, I have the same problem.

**Comment by wanam** [comment] 2023-01-30 08:47
Actually, this is a [known issue](https://github.com/wanam/YouTubeAdAway/issues/129), after adding the revanced patch to hide ad cards, this broke the back-to-exit gesture, so I tried to implement a workaround on 5.0.5 to avoid exiting when the scroll is not at the top of the home page, but it seems the scrolling events I'm hooking are not accurate, thus reporting the false state of the scrolling.

**Comment by cocci810123** [comment] 2023-01-30 13:57
> Actually, this is a [known issue](https://github.com/wanam/YouTubeAdAway/issues/129), after adding the revanced patch to hide ad cards, this broke the back-to-exit gesture, so I tried to implement a workaround on 5.0.5 to avoid exiting when the scroll is not at the top of the home page, but it seems the scrolling events I'm hooking are not accurate, thus reporting the false state of the scrolling.

waiting for a fixed version:)

**Comment by wanam** [comment] 2023-01-30 16:34
I'm still waiting for [the new xposed api](https://github.com/libxposed) that will introduce remote preferences, planned on the next LSposed release, it's a new way to manage config storage, the latest updates of Android OS do NOT allow the "MODE_WORLD_READABLE" flag, so it won't be easy to read the application preferences while hooking...

**Comment by Hayzedpro** [comment] 2023-02-06 20:04
Pls fix back to exit gesture, it's so annoying 😑

**Comment by Dianshii** [comment] 2023-02-07 00:32
I recommend you try the previous version (5.0.3). The card ads won't be removed but the basic functions still work perfectly (in-video ads removal and background play) on 18.02.34 for me. And that's all I need.

**Comment by GabriLex** [comment] 2023-02-07 20:28
Yeah,same

**Comment by Hayzedpro** [comment] 2023-02-08 05:47
> I recommend you try the previous version (5.0.3). The card ads won't be removed but the basic functions still work perfectly (in-video ads removal and background play) on 18.02.34 for me. And that's all I need.

I just did that , I only care about the in-video ads too

**Comment by wanam** [comment] 2023-02-09 17:53
@Hayzedpro 5.0.3 should be good to go if you don't care about the ad cards, the in-video hooking implementation is the same on both versions.
I will try to add an option to disable the ad cards removal once we get the promised update of xposed api to support prefs storage.

**Comment by wanam** [comment] 2023-02-11 17:46
I made "ad cards removal" optional on 5.0.6.
Closing this issue as it's a duplicate of https://github.com/wanam/YouTubeAdAway/issues/129

**Closed as completed by wanam** 2023-02-11 17:46 UTC
