### ISSUE TITLE
Does not work with YT 17.43.xx 

### ISSUE THREAD

**Issue by NiXTheDev** [Xposed-Modules-Repo/ma.wanam.youtubeadaway#4] opened 2022-11-04 20:37 UTC
Title is descriptive on it's own, however yes, background play and pip(picture-in-picture) no longer work on the latest YouTube 17.43.xx
![My currently installed version is 17.43.36, and the mentioned features don't work](https://user-images.githubusercontent.com/105677206/200069558-451dfb86-8ef1-4fd0-84d1-cca772d3527f.png)

**Comment by NiXTheDev** [comment] 2022-11-04 20:56
Sharing the logs below:

[LSPosed Module logs](https://drive.google.com/file/d/1Dn_hF9vCll9nDOzFujobKwU7IVGfk_3l/view?usp=drivesdk)
[LSPosed Verbose logs](https://drive.google.com/file/d/1Dfp33iUlgldjIUOWYpxaHFP6iXxAVwqC/view?usp=drivesdk)

**Comment by wanam** [comment] 2022-11-05 13:41
Duplicate of https://github.com/Xposed-Modules-Repo/ma.wanam.youtubeadaway/issues/3

**Closed as completed by wanam** 2022-11-05 13:41 UTC
